In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [2]:
c = np.random.randn(4,5)
print(c.shape)
print(c[np.newaxis].shape)  # Adding a dimension

(4, 5)
(1, 4, 5)


In [3]:
print(c)

[[-0.46558352  1.24032883  0.58512256 -1.62415055 -0.24634162]
 [ 0.20440478 -0.50950176  0.17405941  0.49855673  0.32213207]
 [ 0.8469645  -1.02279933  2.45348406  0.16129103  0.24759403]
 [ 0.543162   -0.60454242 -1.2138004  -1.48197507  0.86743468]]


In [4]:
print(c[np.newaxis])

[[[-0.46558352  1.24032883  0.58512256 -1.62415055 -0.24634162]
  [ 0.20440478 -0.50950176  0.17405941  0.49855673  0.32213207]
  [ 0.8469645  -1.02279933  2.45348406  0.16129103  0.24759403]
  [ 0.543162   -0.60454242 -1.2138004  -1.48197507  0.86743468]]]


In [5]:
a = np.array([1,2], [3,4])

TypeError: data type not understood

In [6]:
a = np.array([[1,2], [3,4]])

In [7]:
a

array([[1, 2],
       [3, 4]])

In [8]:
print(a)

[[1 2]
 [3 4]]


In [9]:
b=np.array([[2,3], [4,5]]) 

In [10]:
print(b)

[[2 3]
 [4 5]]


In [11]:
np.dot(a,b)

array([[10, 13],
       [22, 29]])

In [12]:
np.multiply(a,b)

array([[ 2,  6],
       [12, 20]])

In [13]:
np.allclose

In [14]:
a = np.array([[1.0, 2.0], [5.0, 4.0]])
b = np.array([[4, 3], [2, 1]])
v = np.array([0.5, 2.0])

In [15]:
a + v

array([[ 1.5,  4. ],
       [ 5.5,  6. ]])

In [16]:
a + b

array([[ 5.,  5.],
       [ 7.,  5.]])

In [17]:
print(a,b)

[[ 1.  2.]
 [ 5.  4.]] [[4 3]
 [2 1]]


In [18]:
print(a)

[[ 1.  2.]
 [ 5.  4.]]


In [19]:
print(b)

[[4 3]
 [2 1]]


In [20]:
z = ([1, 2, 3])

In [21]:
a+z

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [22]:
v.reshape((-1, 1)).shape

(2, 1)

In [23]:
v.shape

(2,)

In [24]:
a + v.reshape((-1, 1))

array([[ 1.5,  2.5],
       [ 7. ,  6. ]])

In [25]:
a + v

array([[ 1.5,  4. ],
       [ 5.5,  6. ]])

In [26]:
r = np.random.random_integers(0, 9)

/Users/atul/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 9 + 1) instead
  """Entry point for launching an IPython kernel.


In [27]:
r = array([[999, 999,   4,   5],
       [999,   4, 999,   2],
       [999,   0,   4, 999]])

NameError: name 'array' is not defined

In [28]:
r=np.array([[999, 999,   4,   5],
       [999,   4, 999,   2],
       [999,   0,   4, 999]])

In [29]:
r

array([[999, 999,   4,   5],
       [999,   4, 999,   2],
       [999,   0,   4, 999]])

In [30]:
r[(np.array([1,2]), np.array([2,2]))]

array([999,   4])

In [31]:
np.array([1,2]), np.array([2,2])

(array([1, 2]), array([2, 2]))

In [32]:
r[[1,2],[2,2]]

array([999,   4])

In [33]:
r[[2,2],[1,2]]

array([0, 4])

In [34]:
x = np.array([1,2,3])

In [35]:
x

array([1, 2, 3])

In [36]:
tx = np.c_[np.ones(num_samples),x]

NameError: name 'num_samples' is not defined

In [37]:
tx = np.c_[np.ones(3),x]

In [38]:
tx

array([[ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.]])

In [39]:
np.ones(3,1)

TypeError: data type not understood

In [40]:
np.ones([3,1])

array([[ 1.],
       [ 1.],
       [ 1.]])

In [41]:
np.ones([3,1]) + x

array([[ 2.,  3.,  4.],
       [ 2.,  3.,  4.],
       [ 2.,  3.,  4.]])

In [42]:
np.hcat(np.ones([3,1]), x)

AttributeError: module 'numpy' has no attribute 'hcat'

In [43]:
np.hcat(np.ones([3,1]), x)

TypeError: hstack() takes 1 positional argument but 2 were given

In [44]:
np.hcat(np.ones([3,1]), [x])

AttributeError: module 'numpy' has no attribute 'hcat'

In [45]:
np.hstack(np.ones([3,1]), [x])

TypeError: hstack() takes 1 positional argument but 2 were given

In [46]:
np.hstack([np.ones([3,1]), x])

ValueError: all the input arrays must have same number of dimensions

In [47]:
np.hstack([np.ones([3,1]), x.reshape(-1,1)])

array([[ 1.,  1.],
       [ 1.,  2.],
       [ 1.,  3.]])

In [48]:
y = np.arr([1,2])

AttributeError: module 'numpy' has no attribute 'arr'

In [49]:
y = np.array([1,2])

In [50]:
y

array([1, 2])

In [51]:
np.dot(y.T,y)

5

In [53]:
for i in y:
    print (i)

1
2


In [54]:
np.array([3,6]).reshape(-1,1)

array([[3],
       [6]])

In [55]:
print(np.array([3,6]).reshape(-1,1))

[[3]
 [6]]


In [56]:
np.array([3,6]).reshape(-1,1).shape

(2, 1)

In [57]:
a

array([[ 1.,  2.],
       [ 5.,  4.]])

In [58]:
y

array([1, 2])

In [59]:
for i,y in enumerate(y):

SyntaxError: unexpected EOF while parsing (<ipython-input-59-bb84c0ed9356>, line 1)

In [60]:
for i, y in enumerate(y):
    print(i, y)

0 1
1 2


In [61]:
A = np.zeros((2,3))

In [62]:
A

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [63]:
A[0][0] = 5

In [64]:
A


array([[ 5.,  0.,  0.],
       [ 0.,  0.,  0.]])